spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/certificatessystem
    username : root
    password : root
  flyway:
    schemas : certificatessystem
    baselineOnMigrate : true
    locations : classpath:sql/migrations
    baselineVersion : 0
  cache:
    jcache:
      config: classpath:ehcache.xml
